trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "##vso[task.setvariable variable=runDownload;]No"

- task: UniversalPackages@0
  displayName: 'Download QA resources (Universal Package artifact)'
  inputs:
    command: download
    vstsFeed: 'pim-poc/QA_Resources'
    vstsFeedPackage:  'qa-resources'
    vstsPackageVersion: '*' # latest - why not just call it latest eh microsoft?!
    downloadDirectory: '$(Build.SourcesDirectory)/QA_Resources'
  condition: eq(variables['runDownload'], 'Yes')

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: PythonScript@0
  inputs:
    scriptSource: filePath
    scriptPath: "./build.py"

- task: UniversalPackages@0
  inputs:
    command: publish
    publishDirectory: '$(Build.SourcesDirectory)/QA_Resources'
    vstsFeedPublish: 'pim-poc/QA_Resources'
    vstsFeedPackagePublish: 'qa-resources'
    packagePublishDescription: 'Post-run QA resource files'



